packages:
  - ./libs/*
  - ./demos/*
  - ./demos/remote-mcp-auth0/*
  - ./examples/*
  - ./packages/*
  - ./tools/aicli
  - "!./demos/remote-mcp-auth0"
  - "!./demos/remote-mcp-auth0/docs"
onlyBuiltDependencies:
  - esbuild
  - workerd
